name: env_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - plotly
  - statsmodels
  - scikit-learn
  - seaborn
  - streamlit
  - pip
  - pip:
      - altair
      - attrs
      - blinker
      - cachetools
      - certifi
      - charset-normalizer
      - click
      - gitdb
      - gitpython
      - idna
      - jinja2
      - jsonschema
      - markdown-it-py
      - markupsafe
      - mdurl
      - plotly-express
      - protobuf
      - pyarrow
      - pydeck
      - referencing
      - requests
      - rich
      - rpds-py
      - tenacity
      - toml
      - toolz
      - urllib3
      - watchdog